### ISSUE TITLE
Nerd font and color scheme used for mac-os preview ?

### ISSUE THREAD

**Issue by VPraharsha03** [fang2hou/starship-gruvbox-rainbow#1]
@fang2hou Thanks for the preset, it looks amazing 🌟

Just one more thing, if you wouldn't mind could you please also share the nerd font and terminal color scheme used in the Mac-OS preview ? as it looks the best among all the previews

**Comment by fang2hou** [comment]
I am using [alacritty](https://github.com/alacritty/alacritty) now.
The font is JetBrainsMono Nerd Font, you can download it from [here](https://www.nerdfonts.com/font-downloads).

<details>

<summary>My alacrity TOML</summary>

```toml
[colors.bright]
black = "#4b4b4b"
blue = "#9ac2bb"
cyan = "#aedea0"
green = "#c8c847"
magenta = "#eaa4b7"
red = "#ff5f4f"
white = "#ffffff"
yellow = "#ffc24b"

[colors.normal]
black = "#282828"
blue = "#80aa9e"
cyan = "#8bba7f"
green = "#b0b846"
magenta = "#d3869b"
red = "#f2594b"
white = "#e2cca9"
yellow = "#e9b143"

[colors.primary]
background = "#282828"
foreground = "#e2cca9"

[font]
size = 15.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 1

[window]
decorations = "full"
dynamic_padding = false
option_as_alt = "OnlyLeft"
resize_increments = true

[window.dimensions]
columns = 180
lines = 35

[window.padding]
x = 12
y = 12
```

</details>
